package com.cbmachinery.aftercareserviceagent.report.dto;

public enum BreakdownKeys {
	ID, DESCRIPTION, BREAKDOWN_TYPE, RISK_LEVEL, REPORTED_DATE, PRODUCT_ID, PRODUCT_NAME, CLIENT_ID, CLIENT_NAME,
	CLIENT_EMAIL, PRIORITY_LEVEL, STATUS, TECHNICIAN_ID, TECHNICIAN_NAME, ROOT_CAUSE, SOLUTION
}
