package com.cbmachinery.aftercareserviceagent.report.dto;

public enum WorksheetKeys {
	ID, DESCRIPTION, REPORTED_DATE, PRODUCT_ID, PRODUCT_NAME, CLIENT_ID, CLIENT_NAME, TASK_STATUS,
	TECHNICIAN_ID, TECHNICIAN_NAME, ASSIGNED_DATE, STARTED_DATE, COMPLETED_DATE, TASK_TYPE
}
